name: Weekly Monitoring Scripts

on:
  schedule:
    - cron: "19 8 * * 0"
  workflow_dispatch:

# Add concurrency control
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  weekly:
    uses: ./.github/workflows/_run-monitoring.yml
    secrets: inherit
    with:
      extra_env: "GITHUB_RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      scripts: |
        yearn/check_endorsed.py
